

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - shared_net
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: prueba
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432
      DISPLAY: ${DISPLAY:-host.docker.internal:0.0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # Montar el socket de X11
    networks:
      - shared_net

volumes:
  postgres_data:

networks:
  shared_net:
    driver: bridge
