services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: prueba
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shared_net  # Aquí agregas la red

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: prueba
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_HOST: db
      DB_PORT: 5432
    networks:
      - shared_net  # Aquí agregas la misma red

volumes:
  postgres_data:

networks:
  shared_net:  # Aquí defines la red
    driver: bridge  # El controlador predeterminado para redes Docker
